# Generated by Django 5.1.6 on 2025-02-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
